### ISSUE TITLE
为姚奕的回复增加更多 emoji

### ISSUE THREAD

**Issue by haitang000** [whiTeLeaf-TL/U1bot#155]
例如:

---

- ❌ 钓鱼在本群处于关闭状态，请看菜单重新打开
- 🎣 正在钓鱼... 🔮 获得运气加成[6]
- 🥳 你钓到了一条虚空 心海，长度为 1145cm
> 可根据鱼的稀有程度变换表情
- 🥱 河累了，等会再来吧
- 💰 你拥有 114514.00 次元币
- 👋 早上好！（略）
- 🔮 中吉 | ★★★★★☆☆ （略）
- 🍲 正在为你找好吃的...
- ✅ 姚奕推荐你吃 （略）

**Comment by wling-art** [comment]
> 例如:
> 
> * ❌ 钓鱼在本群处于关闭状态，请看菜单重新打开
> * 🎣 正在钓鱼... 🔮 获得运气加成[6]
> * 🥳 你钓到了一条虚空 心海，长度为 1145cm
> 
> > 可根据鱼的稀有程度变换表情
> 
> * 🥱 河累了，等会再来吧
> * 💰 你拥有 114514.00 次元币
> * 👋 早上好！（略）
> * 🔮 中吉 | ★★★★★☆☆ （略）
> * 🍲 正在为你找好吃的...
> * ✅ 姚奕推荐你吃 （略）

在苹果emoji的显示我认为会很丑，而且每个设备emoji的样式都不同步
